### ISSUE TITLE
Error if resource not found

### ISSUE THREAD

**Issue by mostafabarmshory** [pluf/cache#2]
If requested resource does not exist, then an error raised?!

`unsupported error in system:exception 'PlufErrorHandlerException' with message 'md5_file(/home/plufir/public_html/storage/tenant/2/spa/78/companies/security-doors): failed to open stream: No such file or directory' in /home/plufir/public_html/vendor/pluf/core/src/Pluf/HTTP/Response/File.php:65 Stack trace: #0 [internal function]: PlufErrorHandler(2, 'md5_file(/home/...', '/home/plufir/pu...', 65, Array) #1 /home/plufir/public_html/vendor/pluf/core/src/Pluf/HTTP/Response/File.php(65): md5_file('/home/plufir/pu...') #2 /home/plufir/public_html/vendor/pluf/cache/src/Cache/Middleware/RFC7234.php(57): Pluf_HTTP_Response_File->hashCode() #3 /home/plufir/public_html/vendor/pluf/core/src/Pluf/Dispatcher.php(82): Cache_Middleware_RFC7234->process_response(Object(Pluf_HTTP_Request), Object(Pluf_HTTP_Response_File)) #4 /home/plufir/public_html/index.php(62): Pluf_Dispatcher::dispatch('companies/secur...') #5 {main}`

A constant value is better.

**Comment by mostafabarmshory** [comment]
Adding a check to verify file. We check file existence before md5 function.
